// filterOptions.js
export const employmentTypes = [
    { value: 'Full-time', label: 'Full Time' },
    { value: 'Part-time', label: 'Part Time' },
    { value: 'Contract', label: 'Contract' },
    { value: 'Other', label: 'Other' }
];

export const usStates = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' }
];

export const companyIndustries = [
    { value: 'Defense and Space Manufacturing', label: 'Defense and Space Manufacturing' },
    { value: 'Computer Hardware Manufacturing', label: 'Computer Hardware Manufacturing' },
    { value: 'Software Development', label: 'Software Development' },
    { value: 'Computer Networking Products', label: 'Computer Networking Products' },
    { value: 'Technology, Information and Internet', label: 'Technology, Information and Internet' },
    { value: 'Semiconductor Manufacturing', label: 'Semiconductor Manufacturing' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Law Practice', label: 'Law Practice' },
    { value: 'Legal Services', label: 'Legal Services' },
    { value: 'Business Consulting and Services', label: 'Business Consulting and Services' },
    { value: 'Biotechnology Research', label: 'Biotechnology Research' },
    { value: 'Medical Practices', label: 'Medical Practices' },
    { value: 'Hospitals and Health Care', label: 'Hospitals and Health Care' },
    { value: 'Pharmaceutical Manufacturing', label: 'Pharmaceutical Manufacturing' },
    { value: 'Veterinary Services', label: 'Veterinary Services' },
    { value: 'Medical Equipment Manufacturing', label: 'Medical Equipment Manufacturing' },
    { value: 'Personal Care Product Manufacturing', label: 'Personal Care Product Manufacturing' },
    { value: 'Retail Apparel and Fashion', label: 'Retail Apparel and Fashion' },
    { value: 'Sporting Goods Manufacturing', label: 'Sporting Goods Manufacturing' },
    { value: 'Retail Groceries', label: 'Retail Groceries' },
    { value: 'Food and Beverage Manufacturing', label: 'Food and Beverage Manufacturing' },
    { value: 'Computers and Electronics Manufacturing', label: 'Computers and Electronics Manufacturing' },
    { value: 'Manufacturing', label: 'Manufacturing' },
    { value: 'Furniture and Home Furnishings Manufacturing', label: 'Furniture and Home Furnishings Manufacturing' },
    { value: 'Retail', label: 'Retail' },
    { value: 'Entertainment Providers', label: 'Entertainment Providers' },
    { value: 'Gambling Facilities and Casinos', label: 'Gambling Facilities and Casinos' },
    { value: 'Travel Arrangements', label: 'Travel Arrangements' },
    { value: 'Hospitality', label: 'Hospitality' },
    { value: 'Restaurants', label: 'Restaurants' },
    { value: 'Spectator Sports', label: 'Spectator Sports' },
    { value: 'Food and Beverage Services', label: 'Food and Beverage Services' },
    { value: 'Movies, Videos, and Sound', label: 'Movies, Videos, and Sound' },
    { value: 'Broadcast Media Production and Distribution', label: 'Broadcast Media Production and Distribution' },
    { value: 'Museums, Historical Sites, and Zoos', label: 'Museums, Historical Sites, and Zoos' },
    { value: 'Artists and Writers', label: 'Artists and Writers' },
    { value: 'Performing Arts', label: 'Performing Arts' },
    { value: 'Recreational Facilities', label: 'Recreational Facilities' },
    { value: 'Banking', label: 'Banking' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Financial Services', label: 'Financial Services' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Investment Banking', label: 'Investment Banking' },
    { value: 'Investment Management', label: 'Investment Management' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Wholesale Building Materials', label: 'Wholesale Building Materials' },
    { value: 'Architecture and Planning', label: 'Architecture and Planning' },
    { value: 'Civil Engineering', label: 'Civil Engineering' },
    { value: 'Aviation and Aerospace Component Manufacturing', label: 'Aviation and Aerospace Component Manufacturing' },
    { value: 'Motor Vehicle Manufacturing', label: 'Motor Vehicle Manufacturing' },
    { value: 'Chemical Manufacturing', label: 'Chemical Manufacturing' },
    { value: 'Machinery Manufacturing', label: 'Machinery Manufacturing' },
    { value: 'Mining', label: 'Mining' },
    { value: 'Oil and Gas', label: 'Oil and Gas' },
    { value: 'Shipbuilding', label: 'Shipbuilding' },
    { value: 'Utilities', label: 'Utilities' },
    { value: 'Textile Manufacturing', label: 'Textile Manufacturing' },
    { value: 'Paper and Forest Product Manufacturing', label: 'Paper and Forest Product Manufacturing' },
    { value: 'Railroad Equipment Manufacturing', label: 'Railroad Equipment Manufacturing' },
    { value: 'Farming', label: 'Farming' },
    { value: 'Ranching', label: 'Ranching' },
    { value: 'Dairy Product Manufacturing', label: 'Dairy Product Manufacturing' },
    { value: 'Primary and Secondary Education', label: 'Primary and Secondary Education' },
    { value: 'Higher Education', label: 'Higher Education' },
    { value: 'Education Administration Programs', label: 'Education Administration Programs' },
    { value: 'Research Services', label: 'Research Services' },
    { value: 'Armed Forces', label: 'Armed Forces' },
    { value: 'Administration of Justice', label: 'Administration of Justice' },
    { value: 'International Affairs', label: 'International Affairs' },
    { value: 'Government Administration', label: 'Government Administration' },
    { value: 'Executive Offices', label: 'Executive Offices' } 
]

export const cities = [
    { value: 'New York', label: 'New York' },
    { value: 'Los Angeles', label: 'Los Angeles' },
    { value: 'Chicago', label: 'Chicago' },
    { value: 'Houston', label: 'Houston' },
    { value: 'Phoenix', label: 'Phoenix' },
    { value: 'Philadelphia', label: 'Philadelphia' },
    { value: 'San Antonio', label: 'San Antonio' },
    { value: 'San Diego', label: 'San Diego' },
    { value: 'Dallas', label: 'Dallas' },
    { value: 'San Jose', label: 'San Jose' },
    { value: 'Austin', label: 'Austin' },
    { value: 'Jacksonville', label: 'Jacksonville' },
    { value: 'Fort Worth', label: 'Fort Worth' },
    { value: 'Columbus', label: 'Columbus' },
    { value: 'Charlotte', label: 'Charlotte' },
    { value: 'San Francisco', label: 'San Francisco' },
    { value: 'Indianapolis', label: 'Indianapolis' },
    { value: 'Seattle', label: 'Seattle' },
    { value: 'Denver', label: 'Denver' },
    { value: 'Washington', label: 'Washington' },
    { value: 'Boston', label: 'Boston' },
    { value: 'El Paso', label: 'El Paso' },
    { value: 'Nashville', label: 'Nashville' },
    { value: 'Detroit', label: 'Detroit' },
    { value: 'Oklahoma City', label: 'Oklahoma City' },
    { value: 'Portland', label: 'Portland' },
    { value: 'Las Vegas', label: 'Las Vegas' },
    { value: 'Memphis', label: 'Memphis' },
    { value: 'Louisville', label: 'Louisville' },
    { value: 'Baltimore', label: 'Baltimore' },
    { value: 'Milwaukee', label: 'Milwaukee' },
    { value: 'Albuquerque', label: 'Albuquerque' },
    { value: 'Tucson', label: 'Tucson' },
    { value: 'Fresno', label: 'Fresno' },
    { value: 'Sacramento', label: 'Sacramento' },
    { value: 'Kansas City', label: 'Kansas City' },
    { value: 'Long Beach', label: 'Long Beach' },
    { value: 'Mesa', label: 'Mesa' },
    { value: 'Atlanta', label: 'Atlanta' },
    { value: 'Colorado Springs', label: 'Colorado Springs' },
    { value: 'Virginia Beach', label: 'Virginia Beach' },
    { value: 'Raleigh', label: 'Raleigh' },
    { value: 'Omaha', label: 'Omaha' },
    { value: 'Miami', label: 'Miami' },
    { value: 'Oakland', label: 'Oakland' },
    { value: 'Minneapolis', label: 'Minneapolis' },
    { value: 'Tulsa', label: 'Tulsa' },
    { value: 'Arlington', label: 'Arlington' },
    { value: 'New Orleans', label: 'New Orleans' },
  ];
  